### ISSUE TITLE
odroid-io crashes nodered

### ISSUE THREAD

**Issue by habakuk1979** [racerxdl/odroid-io#1]
hello!

I am Running **node.js V 12.11.1 on Odroid C2 on Kernel 5.14.19**.

I installed 
npm install johnny-five 

with no problems

then I installed 

npm install odroid-io

with no problems either.

But as soon a node (in my case **node-red-contrib-gio: gpio-in**) uses the **"Odroid-io" plugin**, node-red crashed with:

```
TypeError: Cannot read property 'index' of undefined
    at OdroidIO.normalize (/home/odroid/node_modules/odroid-io/lib/odroid-io.js:182:32)
    at OdroidIO.pinMode (/home/odroid/node_modules/odroid-io/lib/odroid-io.js:189:33)
    at iopluginNode.<anonymous> (/home/odroid/.node-red/node_modules/node-red-contrib-gpio/gpio.js:82:20)
    at iopluginNode.emit [as _emit] (events.js:210:5)
    at iopluginNode.Node.emit (/home/odroid/.nvm/versions/node/v12.11.1/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:181:20)
    at /home/odroid/.node-red/node_modules/node-red-contrib-gpio/lib/iopluginNode.js:38:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:412:9)
    at process.topLevelDomainCallback (domain.js:131:23)
**1 Mar 04:27:06 - [red] Uncaught Exception:
1 Mar 04:27:06 - TypeError: Cannot read property 'index' of undefined**
    at OdroidIO.normalize (/home/odroid/node_modules/odroid-io/lib/odroid-io.js:182:32)
    at OdroidIO.digitalRead (/home/odroid/node_modules/odroid-io/lib/odroid-io.js:225:23)
    at iopluginNode.<anonymous> (/home/odroid/.node-red/node_modules/node-red-contrib-gpio/gpio.js:83:14)
    at iopluginNode.emit [as _emit] (events.js:210:5)
    at iopluginNode.Node.emit (/home/odroid/.nvm/versions/node/v12.11.1/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:181:20)
    at /home/odroid/.node-red/node_modules/node-red-contrib-gpio/lib/iopluginNode.js:38:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:412:9)
    at process.topLevelDomainCallback (domain.js:131:23)
```

Does anyone know how to fix this?

**Comment by habakuk1979** [comment]
hello!

addon: 

I just upgraded from node.js 12.11.1 tp 17.1.0.

now odroid-io not crashing nodered anymore but get the following: ??
weird:

```
error loading plugin odroid-io The module '/home/odroid/node_modules/i2c-bus/build/Release/i2c.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

by the way: deleting the node_modules directory and `npm install` afterwards leads to a mess.

ending up with a lot of missing nodes.
